name: Build and deploy ASP.Net Core app to Azure Web App - globalstore-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./GlobalStore.Api/GlobalStore.Api.csproj

      - name: Build
        run: dotnet build ./GlobalStore.Api/GlobalStore.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./GlobalStore.Api/GlobalStore.Api.csproj --configuration Release --output ./publish --no-build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9860EA788BB94C6CA168315227DC7BFB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_069C8ECE51614EBD8C1D79BA22D8DDDA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_494AA1212AC14250A7FCFDAB6C7CB56B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'globalstore-api'
          slot-name: 'staging'
          package: ./publish
